image:
  file: Dockerfile
 
ports:
  - port: 8080
    onOpen: ignore
  - port: 6080
    onOpen: ignore
  - port: 3000
    onOpen: ignore

vscode:
  extensions:
    - twxs.cmake@0.0.17:aQNzlYa74rJFJ5/BnUF1yA==
    - ms-vscode.cmake-tools@1.5.3:QI2POGDzx7mhyCmZyf/3vg==
    - webfreak.debug@0.25.0:F9uLpAOde6r0l7rgMC8LTQ==
   
